version: '3'

services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: djangodocker
      MYSQL_USER: djangodocker
      MYSQL_PASSWORD: djangodocker
      MYSQL_DATABASE: djangodocker
    ports:
      - 3305:3306
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - data_volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8888:80
    environment:
      MYSQL_ROOT_PASSWORD: djangodocker
      MYSQL_USER: djangodocker
      MYSQL_PASSWORD: djangodocker

  web:
    build: .
    entrypoint: ./docker-compose-entrypoint.sh
    volumes:
      - .:/app
    ports:
      - '8008:8000'
    depends_on:
      - db
      - phpmyadmin

volumes:
  data_volume:
